spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/evrecharge?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8080

stripe:
  public: pk_test_P2ryZyvZrdRTKLREwV3eClqp00rRrpJvpK
  private: sk_test_auHNgS9Kz3VZZ09R9Ub2ROdQ00Ckve8BDY